extensions:
  aws-cdk-helper:
    args:
    - awslabs.cdk-mcp-server@latest
    bundled: null
    cmd: uvx
    description: Documentation of any AWS tool
    enabled: true
    env_keys:
    - FASTMCP_LOG_LEVEL
    envs: {}
    name: aws-cdk-helper
    timeout: 300
    type: stdio
  aws-documentation:
    args:
    - awslabs.aws-documentation-mcp-server@latest
    bundled: null
    cmd: uvx
    description: Documentation of any AWS tool
    enabled: true
    env_keys:
    - FASTMCP_LOG_LEVEL
    - AWS_DOCUMENTATION_PARTITION
    envs: {}
    name: aws-documentation
    timeout: 300
    type: stdio
  ddg-search:
    args:
    - duckduckgo-mcp-server
    bundled: null
    cmd: uvx
    description: Interacting with DuckDuckGo Search for relevant information
    enabled: true
    envs: {}
    name: ddg-search
    timeout: 300
    type: stdio
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  github:
    args:
    - -y
    - '@modelcontextprotocol/server-github'
    bundled: null
    cmd: npx
    description: Interacting with GitHub via personal access token
    enabled: true
    env_keys:
    - GITHUB_TOKEN
    envs: {}
    name: github
    timeout: 300
    type: stdio
GOOSE_ROUTER_TOOL_SELECTION_STRATEGY: vector
GOOSE_MODE: smart_approve
GOOSE_PROVIDER: openrouter
ANTHROPIC_HOST: https://api.anthropic.com
GOOSE_MODEL: anthropic/claude-sonnet-4
